SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE phkapa.phkapa_tickets ADD cost decimal(10,2) DEFAULT 0.00 NULL;
ALTER TABLE phkapa.phkapa_tickets CHANGE cost cost decimal(10,2) DEFAULT 0.00 NULL AFTER product;
ALTER TABLE phkapa.phkapa_tickets_revision ADD cost decimal(10,2) DEFAULT 0.00 NULL;
ALTER TABLE phkapa.phkapa_tickets_revision CHANGE cost cost decimal(10,2) DEFAULT 0.00 NULL AFTER product; 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
